### ISSUE TITLE
Manual processing of month can be processed using Typst standard library

### ISSUE THREAD

**Issue by JamesxX** [jskherman/imprecv#24]
https://github.com/jskherman/imprecv/blob/dfc034563d21e662e155f528b00914237f35f228/utils.typ#L1-L27

This can be achieved like so:
```typ
#let monthname(n, display: "short") = {
  datetime(month: n, day: 1, year: 0).display("[month repr:#display]")
}
```

This will throw on an invalid month so if that isn't desirable you should add another line to check if n is within the range 1 to 12.

**Comment by jskherman** [comment]
Yes, the `datetime.display()` function was used before for formatting but as pointed out in PR #22, Typst still only has English month names as the output. The current state is only a band-aid solution until Typst has proper support for other languages in `datetime.display()`.

**Comment by jskherman** [comment]
Closing this since there is no more input, probably.
