### ISSUE TITLE
Allow to not include Country in Location

### ISSUE THREAD

**Issue by kyawzazaw** [jskherman/imprecv#9]
If I comment out the Country in the value part, it still adds a comma after the Region

**Comment by jskherman** [comment]
Hi, just like in #10 you can also override the [`#addresstext`](https://github.com/jskherman/cv.typ/blob/932217ca0a3f92daed3d6d74d46cd881134a22f4/cv.typ#L72C1-L80C2) and [`#cvheading`](https://github.com/jskherman/cv.typ/blob/932217ca0a3f92daed3d6d74d46cd881134a22f4/cv.typ#L110C1-L118C2) functions for this in `cv.typ` in your example.typ file. For example:

```typst
// Each section function can be overridden by re-declaring it here
#let addresstext(info, uservars) = {
    if uservars.showAddress {
        block(width: 100%)[
            #info.personal.location.city, #info.personal.location.region // <===== Edit the address text
            #v(-4pt)
        ]
    } else {none}
}


// Create layout of the title + contact info
// Just copied this verbatim with no change for new addresstext() function to work
#let cvheading(info, uservars) = {
    align(center)[
        = #info.personal.name
        #addresstext(info, uservars)
        #contacttext(info, uservars)
        // #v(0.5em)
    ]
}
```

You need to redeclare both of these functions in the `example.typ` for it to be overwritten properly.

**Comment by mangkoran** [comment]
@jskherman I think we could several fields optional/won't be shown if user don't provide the YAML key/value. What do you think?

**Comment by jskherman** [comment]
That would be for the best, but I don't think I'll be able to work on this anytime soon. If someone could do a PR along the lines of [phamson02's suggestion](https://github.com/jskherman/cv.typ/pull/1#issuecomment-1910896918)...

**Comment by mangkoran** [comment]
I will try to work on it!

**Comment by jskherman** [comment]
Hi sorry for taking so long, the `country` and other address fields can now be omitted for this with the  [v1.0.1 release](https://github.com/jskherman/imprecv/releases/tag/v1.0.1), pending merge in the Typst packages repo.
